name: Self-Hosted Workflow

on:
  repository_dispatch:
    types: [custom-event]

jobs:
  deploy:
    runs-on: self-hosted
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Install Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y xrdp

    - name: Expose SSH Port
      run: |
        sudo sed -i 's/.*Port 22/Port 2222/' /etc/ssh/sshd_config
        sudo service ssh restart

    - name: Start xrdp Service
      run: sudo service xrdp start

    - name: Show Hostname
